### PR TITLE
Catch backend task errors and display them to the user.

### PR DESCRIPTION
**Pull request by CtrlC-Root**
This pull request improves the error handling of `process_task` tasks in the backend.

* Catch any exceptions thrown in `process_task` once we've retrieved the relevant `session` and `request` rows from the database.
* Modify the web client to display the request output with a different style when a `request` fails.

### CODE REVIEW

**Comment by RohitSat** [comment]
Don't see any issues.

**Comment by sinasabet81** [comment]
Looks like it needs a manual rebase 🙍

**Comment by CtrlC-Root** [comment]
@sinasabet81 can you review this?

**Comment by sinasabet81** [comment]
🚢

**Pull request merged**
