### PR TITLE
Create jokes module

### PR DESCRIPTION
**Pull request by afbenedict**

### CODE REVIEW

**Comment by CtrlC-Root** [comment]
Some formatting and style issues:

* Don't copy and paste `TODO` content. Either fill it in or leave it out.
* Don't add parentheses on conditions (i.e. `if(...):`). This is not idiomatic.

Otherwise the code looks good. @sinasabet81 Did you check the functionality?

**Comment by CtrlC-Root** [comment]
@afbenedict It looks like you'll need to do a rebase to fix the merge conflict in `nitrous-post-create.sh`. Although, given that nitrous.io officially shut down yesterday, I'm not sure if we should even keep those files.

**Comment by sinasabet81** [comment]
@CtrlC-Root I just looked over this for completeness; nitrous going down RIP'd my dev environment 😿

**Comment by afbenedict** [comment]
Fixed merge conflicts and removed TODO statements.

**Pull request merged**
