### PR TITLE
Add weather module

### PR DESCRIPTION
**Pull request by CtrlC-Root**
This pull request adds a new `brutus-module-weather` project with some simple unit and style tests. It also updates the top-level project `Makefile` to run targets in the `brutus-module-weather` project.

### CODE REVIEW

**Comment by RohitSat** [comment]
Looks good.

**Comment by izzyleung** [comment]
In the file `src/brutus-module-weather/brutus_module_weather/console.py`

remember to change the port number

**Comment by CtrlC-Root** [comment]
@izzyleung nice, I fixed that.

**Comment by izzyleung** [comment]
@CtrlC-Root 

Probably it would be a great idea to add a config file to route the ports

**Comment by CtrlC-Root** [comment]
It's just a convenience for someone doing local development so I'm not very concerned about it. The actual port numbers are overwritten anyways inside the relevant upstart configuration file (i.e. `vagrant/web-upstart-brutus-module-weather.conf`).

**Comment by CtrlC-Root** [comment]
@RohitSat @sinasabet81 @afbenedict @FTD007 Can I get one of you to review this?

**Pull request merged**
